openapi: 3.0.0
info:
  title: BRAINCHAIN API Documentation
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/CESAWALLMAGAZINE/Connections_trial/1.0.0
  - url: https://api.example.com/v1
paths:
  /connections:
    get:
      summary: Get Connections
      description: Retrieve a list of connections for the user.
      parameters:
        - name: filter
          in: query
          description: Filter by category (e.g., `all`, `web`, `uiux`, `dataScience`, `projectManagement`). Optional.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    role:
                      type: string
                    location:
                      type: string
                    age:
                      type: string
                    skills:
                      type: array
                      items:
                        type: string
                    level:
                      type: integer
                    profileImage:
                      type: string
      security:
        - bearerAuth: []

  /connections/{connectionId}:
    get:
      summary: Get Connection Details
      description: Retrieve the details of a specific connection.
      parameters:
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  role:
                    type: string
                  location:
                    type: string
                  age:
                    type: string
                  skills:
                    type: array
                    items:
                      type: string
                  level:
                    type: integer
                  profileImage:
                    type: string
      security:
        - bearerAuth: []

  /connections/{connectionId}/message:
    post:
      summary: Send Message to Connection
      description: Send a message to a connection.
      parameters:
        - name: connectionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT